Repository Nullus157/async-compression, pull requests merged in 2023-05, with the labels that each got.

#200 docs: add CHANGELOG file
  CHANGELOG.md
Labels: A-semver-norelease

#198 chore: update repo links
  Cargo.toml
  README.md
Labels: A-semver-norelease

#203 use automatic doc cfg for features
  src/lib.rs
  src/macros.rs
Labels: A-semver-norelease

#202 ci: cache dependencies in all exhaustive jobs
  .github/workflows/exhaustive.yml
Labels: A-semver-norelease

#204 dependabot: only update deps on breaking changes
  .github/dependabot.yml
Labels: A-semver-norelease

#209 chore: update ntest to 0.9
  Cargo.lock
  Cargo.toml
Labels: A-semver-norelease

#215 chore: remove implicit empty default feature
  Cargo.toml
Labels: A-semver-norelease

#134 Add ZstdEncoder::with_quality_and_params to enable compression parameters
  src/codec/zstd/encoder.rs
  src/lib.rs
  src/macros.rs
Labels: A-sember-minor

#216 async-compression 0.4.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
Labels: A-semver-major

#225 Use `cargo-nextest` to speedup testing
  .github/workflows/base.yml
  .github/workflows/coverage.yml
  .github/workflows/exhaustive.yml
  .github/workflows/nightly.yml
Labels: A-semver-norelease
